[supabase]
SUPABASE_URL = "https://fppgfktxvzfknulatxzh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcGdma3R4dnpma251bGF0eHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzQxMDksImV4cCI6MjA3MjU1MDEwOX0.e-UVSSPGmFhs2zIuDO_lw4-KV1ori1ESbG5rK1SVrCM"
cook = "laclavesupersegura"
JWT = "eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3a3Zmb2x2aWJkb3h2bmhzZmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTE0OTQsImV4cCI6MjA1OTE2NzQ5NH0"
